#!/usr/bin/env ruby

require 'rubygems'

Dir.glob(File.join("vendor", "gems", "*", "lib")).each do |lib|
  $LOAD_PATH.unshift(File.expand_path(lib))
end

require 'tilt'
require 'fssm'
require 'fileutils'

class Watcher
	def initialize(src, dest)
		@src = src
		@dest = dest
	end
	
	def sync(base, relative)
		path = File.split(relative)[0]
		path = path=='.' ? '' : path+'/'
		
		name = File.basename relative, '.*'
		
		in_file = "#{@src}/#{relative}"
		out_file = "#{@dest}/#{relative}"
		out_dir = File.dirname out_file
		is_new = !File.exists?(out_file)
		
		if File.directory? in_file
			FileUtils.mkdir_p out_file if !File.directory? out_file
		
		
		elsif File.file? in_file
			FileUtils.mkdir_p out_dir if !File.directory? out_dir
			
			engine = Tilt[in_file]
			if not engine.nil? and template = engine.new(in_file)
				out_file = "#{@dest}/#{path}#{name}.#{ext(engine)}"
				is_new = !File.exists?(out_file)
				file = File.open out_file, "wb"
				begin
					file.write template.render
				rescue Exception => e
					puts e
					$stdout.flush
				end
				file.close
			else
				FileUtils.copy in_file, out_file
			end
		end
		
		puts (is_new ? "C " : "U ")+relative
		$stdout.flush
	end
	
	def delete(base, relative)
		path = File.split(relative)[0]
		name = File.basename relative, '.*'
		
		in_file = "#{@src}/#{relative}"
		out_file = "#{@dest}/#{relative}"
		out_dir = File.dirname out_file
		
		engine = Tilt[in_file]
		if not engine.nil?
			out_file = "#{@dest}/#{path}/#{name}.html"
		end
		
		FileUtils.rm_rf out_file if File.exists? out_file
		
		puts "D #{relative}"
		$stdout.flush
	end
	
private
	def ext(engine)
		case engine.to_s
		when 'Tilt::SassTemplate',
		     'Tilt::ScssTemplate',
		     'Tilt::LessTemplate'
			return 'css'
		when 'Tilt::CoffeeScriptTemplate'
			return 'js'
		end
		
		'html'
	end
end

if ARGV.length != 2
	abort "You didn't properly specify your paths. Try `spectator src dest` instead."
end

src = File.expand_path ARGV[0]
dest = File.expand_path ARGV[1]

watcher = Watcher.new src, dest

Dir["#{src}/**/*"].each do |file|
	relative = file.sub(/^#{src}\/?/, '')
	watcher.sync src, relative
end

FSSM.monitor(src, '**/*', :directories => true) do
	create do |base, relative, type|
		watcher.sync base, relative
	end
	update do |base, relative, type|
		watcher.sync base, relative
	end
	delete do |base, relative, type|
		watcher.delete base, relative
	end
end